### ISSUE TITLE
time:inXSDDateTime deprecated in OWL-TIME

### ISSUE THREAD

**Issue by miekeGR** [AusBIGG/abis#14]
Having time:inXSDDateTime available as a time:TemporalEntity data type option here https://ausbigg.github.io/abis/specification.html#_temporality is very useful for us processing legacy data. However, I noted that this data type has been deprecated in the W3C spec https://www.w3.org/TR/owl-time/#time:Instant. Will this create issues for generating ABIS data?

**Comment by nicholascar** [comment]
No, don't worry about it. It's a silly decision to not allow more flexible formats, for all the reasons we have discussed to death, and if we allow it, we allow it, whatever OWL TIME says! So we will...

**Comment by miekeGR** [comment]
Wonderful!! Thanks @nicholascar
