### ISSUE TITLE
corrections spelling and grammar

### ISSUE THREAD

**Issue by lalewis1** [AusBIGG/abis#18]
Found a few small typos and issues as I was reading through.
| section | issue | suggested correction |
| -- | -- | -- |
| 5.5.6 | ues | use
| 5.4 | goe: | geo:
| 5.6 | an time:Instant | a time:Instant
| 5.8 | related | relates
| 5.8 (diagram) | prov:qualifiedAssociation | prov:qualifiedAttribution
| 7.0 | IDN Role Codes URI does not resolve | should be https://linked.data.gov.au/def/data-roles
| 9.2 | performing validation section is empty

**Comment by nicholascar** [comment]
Most issues addressed and last one handed off to Issue #20
