### ISSUE TITLE
Broken image on Overview page

### ISSUE THREAD

**Issue by kheerand** [AusBIGG/abis#2]
The diagram describing the parts of ABIS is broken when viewed from https://ausbigg.github.io/abis/overview.html

![image](https://user-images.githubusercontent.com/7500646/173983249-9b5b721d-9d9e-48c0-afc4-c3b171583b87.png)

It displays ok when viewed from https://github.com/AusBIGG/abis/blob/master/overview/_overview.adoc

**Comment by nicholascar** [comment]
Long since resolved:

![Uploading image.png…]()
