### ISSUE TITLE
ABIS references to https://surroundaustralia.github.io/prof-roles/

### ISSUE THREAD

**Issue by kheerand** [AusBIGG/abis#4]
Nick,

https://github.com/AusBIGG/abis/blob/master/standard/_standard.adoc#abis-parts contains a number of references to https://surroundaustralia.github.io/prof-roles/.  Is this the authoritative source for the prof-roles or is there a more definitive source for these?

**Comment by nicholascar** [comment]
I've re-implemented the Prof Roles vocab at https://agldwg.github.io/prof-roles/, so that can be referenced instead of the former one.

**Comment by kheerand** [comment]
Updated links
