### ISSUE TITLE
Broken links to linked.data.gov.au

### ISSUE THREAD

**Issue by kheerand** [AusBIGG/abis#5]
The following links on [ABIS Standard’s Definition](https://ausbigg.github.io/abis/standard.html) are broken/not working.  I think this is an issue on the linked.data.gov.au side, but not sure.

- Specification: https://linked.data.gov.au/def/abis/specification
- Validator: https://linked.data.gov.au/def/abis/validator
- JSON-LD Context: https://linked.data.gov.au/def/abis/jsonldcontext

**Comment by fontikar** [comment]
Hi ABIS team! Thanks for creating the helpful documentation! 
As I was reading I found another broken link in the Overview documtatation - its super relevant for submitting RDF files! 

https://gateway.bdr.gov.au/ 

Thanks again!

**Comment by nicholascar** [comment]
Specification now at just https://linked.data.gov.au/def/abis but also https://linked.data.gov.au/def/abis/spec for legacy.

Validator working at https://linked.data.gov.au/def/abis/validator

JSON-LD context at https://linked.data.gov.au/def/abis/context.json

Portal at https://abis.dev.kurrawong.net/ for the moment - likly mid 2024, when the Department may take it over and change location
